# Bypass the default shell on systems where it cannot be changed
# shell /usr/local/bin/zsh

font_size 18.0

font_family MesloLGS NF

scrollback_lines 20000

confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Catppuccin Kitty Diff Macchiato
include current-theme.conf
# END_KITTY_THEME
